# Generated by Django 5.2.11 on 2026-02-10 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=8)),
                ('term', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='icd9.concept')),
            ],
        ),
    ]
