default_language_version:
  python: python3.12

repos:
  - repo: local
    hooks:
    - id: check
      name: check
      entry: just check
      language: system
      types: [python]
      require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: debug-statements
    - id: check-ast
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: detect-private-key

  - repo: https://github.com/rtts/djhtml
    rev: 8577ec017145d76a0b954ebb7cb3169d4303014c # v3.0.8
    hooks:
      - id: djhtml
        entry: djhtml --tabwidth 2 # Use a tabwidth of 2 for HTML files
        files: ^templates/.*\.html$ # Indent only HTML files in template directories

  - repo: local
    hooks:
    - id: shellcheck
      name: shellcheck
      description: Test shell scripts with shellcheck
      entry: shellcheck
      language: system
      types: [shell]
      args: [-e, SC1091]

exclude: coding_systems/snomedct/parser_utils/
