# Generated by Django 3.0.4 on 2020-03-27 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('read_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('unknown_field_1', models.CharField(max_length=1)),
                ('unknown_field_2', models.CharField(max_length=1)),
                ('another_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctv3.Concept')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('unknown_field_4', models.CharField(max_length=1)),
                ('name_1', models.CharField(max_length=30)),
                ('name_2', models.CharField(max_length=60, null=True)),
                ('name_3', models.CharField(max_length=198, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptTermMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unknown_field_5', models.CharField(max_length=1)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctv3.Concept')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctv3.Term')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unknown_field_3', models.CharField(max_length=2)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='ctv3.Concept')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='ctv3.Concept')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='children',
            field=models.ManyToManyField(related_name='parents', through='ctv3.ConceptHierarchy', to='ctv3.Concept'),
        ),
        migrations.AddField(
            model_name='concept',
            name='terms',
            field=models.ManyToManyField(related_name='concepts', through='ctv3.ConceptTermMapping', to='ctv3.Term'),
        ),
    ]
