# Generated by Django 5.2.4 on 2025-07-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctv3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawconcept',
            name='children',
            field=models.ManyToManyField(related_name='parents', through='ctv3.RawConceptHierarchy', through_fields=('parent', 'child'), to='ctv3.rawconcept'),
        ),
    ]
