# Generated by Django 3.1.1 on 2020-09-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctv3sctmap2", "0001_initial"),
        ("ctv3", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawConcept",
            fields=[
                (
                    "read_code",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("C", "Current"),
                            ("E", "Extinct"),
                            ("O", "Optional"),
                            ("R", "Redundant"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "unknown_field_2",
                    models.CharField(
                        choices=[
                            ("A", "Unknown field 2: A"),
                            ("A", "Unknown field 2: N"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="concept",
            name="another_concept",
        ),
        migrations.RemoveField(
            model_name="concept",
            name="children",
        ),
        migrations.RemoveField(
            model_name="concept",
            name="terms",
        ),
        migrations.RenameModel(
            old_name="ConceptHierarchy",
            new_name="RawConceptHierarchy",
        ),
        migrations.RenameModel(
            old_name="ConceptTermMapping",
            new_name="RawConceptTermMapping",
        ),
        migrations.RenameModel(
            old_name="Term",
            new_name="RawTerm",
        ),
    ]
