# Generated by Django 3.0.7 on 2020-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctv3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='read_code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='concept',
            name='status',
            field=models.TextField(choices=[('C', 'Current'), ('E', 'Extinct'), ('O', 'Optional'), ('R', 'Redundant')]),
        ),
        migrations.AlterField(
            model_name='concept',
            name='unknown_field_2',
            field=models.TextField(choices=[('A', 'Unknown field 2: A'), ('A', 'Unknown field 2: N')]),
        ),
        migrations.AlterField(
            model_name='concepthierarchy',
            name='list_order',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concepttermmapping',
            name='term_type',
            field=models.TextField(choices=[('P', 'Preferred'), ('S', 'Synonym')]),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.TextField(choices=[('C', 'Status: C (Current?)'), ('O', 'Status: O (Optional?)')]),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
