# Generated by Django 3.1.1 on 2020-09-28 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctv3", "0002_auto_20200928_1208"),
        ("ctv3sctmap2", "0002_auto_20200928_1208"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Concept",
        ),
        migrations.AddField(
            model_name="rawconcept",
            name="another_concept",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ctv3.rawconcept"
            ),
        ),
        migrations.AddField(
            model_name="rawconcept",
            name="children",
            field=models.ManyToManyField(
                related_name="parents",
                through="ctv3.RawConceptHierarchy",
                to="ctv3.RawConcept",
            ),
        ),
        migrations.AddField(
            model_name="rawconcept",
            name="terms",
            field=models.ManyToManyField(
                related_name="concepts",
                through="ctv3.RawConceptTermMapping",
                to="ctv3.RawTerm",
            ),
        ),
        migrations.AlterField(
            model_name="rawconcepthierarchy",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_links",
                to="ctv3.rawconcept",
            ),
        ),
        migrations.AlterField(
            model_name="rawconcepthierarchy",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_links",
                to="ctv3.rawconcept",
            ),
        ),
        migrations.AlterField(
            model_name="rawconcepttermmapping",
            name="concept",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ctv3.rawconcept"
            ),
        ),
    ]
