# Generated by Django 3.1.1 on 2020-09-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctv3", "0003_auto_20200928_1208"),
    ]

    operations = [
        migrations.CreateModel(
            name="TPPConcept",
            fields=[
                (
                    "read_code",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TPPRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.IntegerField()),
                (
                    "ancestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descendant_relationships",
                        to="ctv3.tppconcept",
                    ),
                ),
                (
                    "descendant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestor_relationships",
                        to="ctv3.tppconcept",
                    ),
                ),
            ],
        ),
    ]
