# Generated by Django 2.2.11 on 2020-04-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Codelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('coding_system_id', models.CharField(choices=[('bnf', 'Pseudo BNF'), ('ctv3', 'Clinical Terms Version 3 (Read V3)'), ('readv2', 'Read V2'), ('snomedct', 'SNOMED CT')], max_length=32)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codelists', to='codelists.Publisher')),
            ],
            options={
                'unique_together': {('publisher', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CodelistVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_str', models.CharField(max_length=12)),
                ('definition', models.TextField()),
                ('codelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='codelists.Codelist')),
            ],
            options={
                'unique_together': {('codelist', 'version_str')},
            },
        ),
    ]
