# Generated by Django 2.2.11 on 2020-04-20 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opencodelists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Codelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('coding_system_id', models.CharField(choices=[('bnf', 'Pseudo BNF'), ('ctv3', 'CTV3 (Read V3)'), ('readv2', 'Read V2'), ('snomedct', 'SNOMED CT')], max_length=32, verbose_name='Coding system')),
                ('version_str', models.CharField(max_length=12, verbose_name='Version')),
                ('description', models.TextField()),
                ('methodology', models.TextField()),
                ('csv_data', models.TextField(verbose_name='CSV data')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codelists', to='opencodelists.Project')),
            ],
            options={
                'unique_together': {('project', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SignOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('codelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoffs', to='codelists.Codelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('codelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='codelists.Codelist')),
            ],
        ),
    ]
