# Generated by Django 3.0.7 on 2020-07-22 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0004_auto_20200722_1437"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodelistVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_str",
                    models.CharField(max_length=12, verbose_name="Version"),
                ),
                ("csv_data", models.TextField(verbose_name="CSV data")),
                ("is_draft", models.BooleanField(default=True)),
                (
                    "codelist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="codelists.Codelist",
                    ),
                ),
            ],
            options={
                "unique_together": {("codelist", "version_str")},
            },
        ),
    ]
