# Generated by Django 3.0.7 on 2020-07-22 14:37

from django.db import migrations


def forwards(apps, schema_editor):
    Codelist = apps.get_model("codelists", "Codelist")

    for cl in Codelist.objects.all():
        cl.versions.create(
            version_str=cl.version_str, csv_data=cl.csv_data, is_draft=False
        )


def backwards(apps, schema_editor):
    Codelist = apps.get_model("codelists", "Codelist")

    for cl in Codelist.objects.all():
        clv = cl.versions.order_by("version_str").last()
        cl.version_str = clv.version_str
        cl.csv_data = clv.csv_data
        cl.save()


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0005_codelistversion'),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
