# Generated by Django 3.1 on 2020-08-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0007_auto_20200722_1438"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelistversion",
            name="definition",
            field=models.JSONField(null=True, default={}),
        ),
    ]
