# Generated by Django 3.0.7 on 2020-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0007_auto_20200722_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelist',
            name='coding_system_id',
            field=models.TextField(choices=[('bnf', 'Pseudo BNF'), ('ctv3', 'CTV3 (Read V3)'), ('ctv3tpp', 'CTV3 (Read V3) with TPP extensions'), ('dmd', 'Dictionary of Medicines and Devices'), ('icd10', 'ICD-10'), ('readv2', 'Read V2'), ('snomedct', 'SNOMED CT')], verbose_name='Coding system'),
        ),
        migrations.AlterField(
            model_name='codelist',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='codelistversion',
            name='version_str',
            field=models.TextField(verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='text',
            field=models.TextField(),
        ),
    ]
