# Generated by Django 3.1.3 on 2020-11-10 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0008_swap_name_for_slug_in_codelist_uniqueness_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codelistversion",
            name="csv_data",
            field=models.TextField(null=True, verbose_name="CSV data"),
        ),
        migrations.CreateModel(
            name="CodeObj",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=18)),
                (
                    "codelist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_objs",
                        to="codelists.codelistversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DefinitionRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("+", "Included with descendants"),
                            ("-", "Excluded with descendants"),
                        ],
                        default="?",
                        max_length=3,
                    ),
                ),
                (
                    "codelist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="codelists.codelistversion",
                    ),
                ),
            ],
            options={
                "unique_together": {("codelist", "code")},
            },
        ),
    ]
