# Generated by Django 3.1.1 on 2020-10-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencodelists", "0002_auto_20200424_1017"),
        ("codelists", "0008_swap_name_for_slug_in_codelist_uniqueness_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodelistLabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("is_current", models.BooleanField()),
                (
                    "codelist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="codelists.codelist",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codelist_labels",
                        to="opencodelists.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "slug")},
            },
        ),
    ]
