# Generated by Django 3.1.3 on 2020-11-12 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencodelists", "0002_auto_20200424_1017"),
        ("codelists", "0009_auto_20201110_1957"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelist",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codelists",
                to="opencodelists.organisation",
            ),
        ),
    ]
