# Generated by Django 3.1.1 on 2020-10-08 09:12

from django.db import migrations


def create_codelist_names(apps, schema_editor):
    Codelist = apps.get_model("codelists", "Codelist")

    for codelist in Codelist.objects.all():
        codelist.labels.create(
            name=codelist.name,
            slug=codelist.slug,
            project=codelist.project,
            is_current=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0009_codelistlabel"),
    ]

    operations = [migrations.RunPython(create_codelist_names)]
