# Generated by Django 3.1.3 on 2020-11-12 08:57

from django.db import migrations


def set_codelist_organisation(apps, schema_editor):
    """For each Codelist, set organisation field based on project field."""

    Organisation = apps.get_model("opencodelists", "Organisation")
    Codelist = apps.get_model("codelists", "Codelist")

    for cl in Codelist.objects.all():
        p = cl.project
        o, _ = Organisation.objects.get_or_create(
            slug=p.slug, defaults={"name": p.name, "url": p.url}
        )
        cl.organisation = o
        cl.save()


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0010_codelist_organisation"),
    ]
    operations = [migrations.RunPython(set_codelist_organisation)]
