# Generated by Django 3.1.3 on 2020-11-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opencodelists", "0002_auto_20200424_1017"),
        ("codelists", "0011_auto_20201112_0857"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="codelist",
            unique_together={("organisation", "name", "slug")},
        ),
    ]
