# Generated by Django 3.1.3 on 2020-11-12 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencodelists", "0002_auto_20200424_1017"),
        ("codelists", "0012_auto_20201112_0924"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codelist",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codelists",
                to="opencodelists.project",
            ),
        ),
    ]
