# Generated by Django 3.1.3 on 2020-11-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0013_auto_20201112_0938"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codelist",
            name="project",
        ),
    ]
