# Generated by Django 3.1.3 on 2020-11-16 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencodelists", "0006_remove_user_organisation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("codelists", "0014_remove_codelist_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelist",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codelists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="codelist",
            unique_together={
                ("organisation", "name", "slug"),
                ("user", "name", "slug"),
            },
        ),
    ]
