# Generated by Django 3.1.3 on 2020-11-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0015_auto_20201116_1744"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="codelist",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("organisation_id__isnull", False), ("user_id__isnull", True)
                    ),
                    models.Q(
                        ("organisation_id__isnull", True), ("user_id__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="codelists_codelist_organisation_xor_user",
            ),
        ),
    ]
