# Generated by Django 3.1.3 on 2020-11-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0016_auto_20201116_1754"),
    ]

    operations = [
        migrations.RenameField(
            model_name="codelistversion",
            old_name="version_str",
            new_name="tag",
        ),
        migrations.AlterUniqueTogether(
            name="codelistversion",
            unique_together={("codelist", "tag")},
        ),
    ]
