# Generated by Django 3.1.3 on 2020-11-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0018_auto_20201119_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelistversion',
            name='tag',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
