# Generated by Django 3.1.3 on 2020-11-19 09:32

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0019_auto_20201119_0930"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2020, 11, 19, 9, 32, 9, 901186, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="codelist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="codelistversion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2020, 11, 19, 9, 32, 19, 101526, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="codelistversion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
