# Generated by Django 3.1.3 on 2020-11-19 09:32

from django.db import migrations


def set_created_at(apps, schema_editor):
    Codelist = apps.get_model("codelists", "Codelist")
    CodelistVersion = apps.get_model("codelists", "CodelistVersion")

    for cl in Codelist.objects.all():
        first_clv = cl.versions.order_by("tag").first()
        date_str = first_clv.tag[:10]
        cl.created_at = date_str
        cl.save()

    for clv in CodelistVersion.objects.all():
        date_str = clv.tag[:10]
        clv.created_at = date_str
        clv.save()


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0020_auto_20201119_0932'),
    ]

    operations = [migrations.RunPython(set_created_at)]
