# Generated by Django 3.1.3 on 2020-11-22 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("codelists", "0021_auto_20201119_0932"),
    ]

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="codeobj",
            old_name="codelist",
            new_name="version",
        ),
        migrations.AddField(
            model_name="codelistversion",
            name="draft_owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="codeobj",
            name="status",
            field=models.CharField(
                choices=[
                    ("?", "Undecided"),
                    ("!", "In conflict"),
                    ("+", "Included with descendants"),
                    ("(+)", "Included by ancestor"),
                    ("-", "Excluded with descendants"),
                    ("(-)", "Excluded by ancestor"),
                ],
                default="?",
                max_length=3,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="codeobj",
            unique_together={("version", "code")},
        ),
        migrations.DeleteModel(
            name="DefinitionRule",
        ),
        migrations.AddField(
            model_name="searchresult",
            name="code_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="codelists.codeobj",
            ),
        ),
        migrations.AddField(
            model_name="searchresult",
            name="search",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="codelists.search",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="searches",
                to="codelists.codelistversion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="searchresult",
            unique_together={("search", "code_obj")},
        ),
        migrations.AlterUniqueTogether(
            name="search",
            unique_together={("version", "slug")},
        ),
    ]
