# Generated by Django 3.1.3 on 2020-11-22 14:48

from django.db import migrations


def move_drafts(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0022_auto_20201122_1444"),
    ]

    operations = [migrations.RunPython(move_drafts)]
