# Generated by Django 3.1.3 on 2020-11-22 14:48

from django.db import migrations


def move_drafts(apps, schema_editor):
    Codelist = apps.get_model("codelists", "Codelist")
    SearchResult = apps.get_model("codelists", "SearchResult")
    DraftCodelist = apps.get_model("builder", "DraftCodelist")

    for draft in DraftCodelist.objects.all():
        # Create a Codelist and CodelistVersion
        codelist = Codelist.objects.create(
            name=draft.name,
            slug=draft.slug,
            user=draft.owner,
            coding_system_id=draft.coding_system_id,
        )
        version = codelist.versions.create(draft_owner=draft.owner)

        # Copy CodeObjs to new CodelistVersion
        for draft_code_obj in draft.codes.all():
            version.code_objs.create(
                code=draft_code_obj.code, status=draft_code_obj.status
            )

        # Copy Searches and SearchResults to new CodelistVersion
        for draft_search in draft.searches.all():
            search = version.searches.create(
                term=draft_search.term, slug=draft_search.slug
            )
            search_codes = draft_search.results.values_list("code", flat=True)
            code_obj_ids = version.code_objs.filter(code__in=search_codes).values_list(
                "id", flat=True
            )
            SearchResult.objects.bulk_create(
                SearchResult(search=search, code_id=id) for id in code_obj_ids
            )


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0022_auto_20201122_1444"),
    ]

    operations = [migrations.RunPython(move_drafts)]
