# Generated by Django 3.1.3 on 2020-11-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0023_auto_20201122_1448"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelistversion",
            name="discarded",
            field=models.BooleanField(default=False),
        ),
    ]
