# Generated by Django 3.1.3 on 2020-11-26 17:01

# This migration fixes the CodelistVersions created from DraftCodelists in migration
# 0023.  That migration did not create SearchResult objects, because on line 32
#
#   search_codes = draft_search.results.values_list("code", flat=True)
#
#  should have been
#
#   search_codes = draft_search.results.values_list("code__code", flat=True)
#
# That is, the original query returned the database IDs of the Codes in the builder
# app, and not the code attributes of those Codes.

from django.db import migrations


def move_drafts_properly(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0025_auto_20201123_1708"),
    ]

    operations = [migrations.RunPython(move_drafts_properly)]
