# Generated by Django 3.1.5 on 2021-01-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0026_auto_20201126_1701"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codelist",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
