# Generated by Django 3.1.5 on 2021-02-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0028_collaboration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codelist",
            name="coding_system_id",
            field=models.CharField(
                choices=[
                    ("bnf", "Pseudo BNF"),
                    ("ctv3", "CTV3 (Read V3)"),
                    ("ctv3tpp", "CTV3 (Read V3) with TPP extensions"),
                    ("dmd", "Dictionary of Medicines and Devices"),
                    ("icd10", "ICD-10"),
                    ("null", "No coding system"),
                    ("opcs4", "OPCS-4"),
                    ("readv2", "Read V2"),
                    ("snomedct", "SNOMED CT"),
                ],
                max_length=32,
                verbose_name="Coding system",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="url",
            field=models.URLField(max_length=1000),
        ),
    ]
