# Generated by Django 3.1.7 on 2021-04-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0030_auto_20210412_0947"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codelist",
            name="coding_system_id",
            field=models.CharField(
                choices=[
                    ("bnf", "Pseudo BNF"),
                    ("ctv3", "CTV3 (Read V3)"),
                    ("dmd", "Dictionary of Medicines and Devices"),
                    ("icd10", "ICD-10"),
                    ("null", "No coding system"),
                    ("opcs4", "OPCS-4"),
                    ("readv2", "Read V2"),
                    ("snomedct", "SNOMED CT"),
                ],
                max_length=32,
                verbose_name="Coding system",
            ),
        ),
    ]
