# Generated by Django 3.1.8 on 2021-04-29 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opencodelists", "0007_auto_20210114_1139"),
        ("codelists", "0032_auto_20210423_1116"),
    ]

    operations = [
        migrations.CreateModel(
            name="Handle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("is_current", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codelist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handles",
                        to="codelists.codelist",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handles",
                        to="opencodelists.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="handle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("organisation_id__isnull", False), ("user_id__isnull", True)
                    ),
                    models.Q(
                        ("organisation_id__isnull", True), ("user_id__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="codelists_handle_organisation_xor_user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="handle",
            unique_together={
                ("user", "name", "slug"),
                ("organisation", "name", "slug"),
            },
        ),
    ]
