# Generated by Django 3.2.1 on 2021-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0035_auto_20210429_1035"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelistversion",
            name="status",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
