# Generated by Django 3.2.1 on 2021-05-11 14:46

from django.db import migrations


def set_status(apps, schema_editor):
    CodelistVersion = apps.get_model("codelists", "CodelistVersion")
    for version in CodelistVersion.objects.all():
        if version.draft_owner:
            version.status = "draft"
        else:
            version.status = "published"
        version.save()


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0036_codelistversion_status"),
    ]

    operations = [migrations.RunPython(set_status)]
