# Generated by Django 3.2.1 on 2021-05-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0037_auto_20210511_1446"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codelistversion",
            name="is_draft",
        ),
        migrations.AlterField(
            model_name="codelistversion",
            name="status",
            field=models.CharField(max_length=12),
        ),
    ]
