# Generated by Django 3.2.3 on 2021-05-19 14:01

from django.db import migrations


def delete_discarded_versions(apps, schema_editor):
    CodelistVersion = apps.get_model("codelists", "CodelistVersion")
    CodelistVersion.objects.filter(discarded=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0038_auto_20210511_1455"),
    ]

    operations = [migrations.RunPython(delete_discarded_versions)]
