# Generated by Django 3.2.3 on 2021-05-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0039_auto_20210519_1401"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codelistversion",
            name="discarded",
        ),
    ]
