# Generated by Django 3.2.3 on 2021-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0040_remove_codelistversion_discarded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codelistversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("under review", "Under Review"),
                    ("published", "Published"),
                ],
                max_length=12,
            ),
        ),
    ]
