# Generated by Django 3.2.8 on 2022-01-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0046_alter_handle_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handle",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name="search",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
