# Generated by Django 4.0.3 on 2022-03-17 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("codelists", "0048_fix_github_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelistversion",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
