# Generated by Django 4.0.3 on 2022-03-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0050_set_codelistversion_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codelistversion",
            name="draft_owner",
        ),
    ]
