# Generated by Django 4.0.3 on 2022-03-21 15:33

from django.db import migrations


def set_author_for_under_review_versions(apps, schema_editor):
    CodelistVersion = apps.get_model("codelists", "CodelistVersion")
    User = apps.get_model("opencodelists", "User")
    # Find all under-review versions with no author
    versions_under_review = CodelistVersion.objects.filter(
        author__isnull=True, status="under review"
    )
    for version in versions_under_review:
        # If the codelist's current owner is a user, assign this under-review version to them
        current_owner = version.codelist.handles.filter(is_current=True).first().user
        if current_owner:
            version.author = (
                version.codelist.handles.filter(is_current=True).first().user
            )
        else:
            # If this is an organisation codelist, and there is only one user in the codelist's
            # handles, assign the version to them
            user_handles = (
                version.codelist.handles.filter(user__isnull=False)
                .values_list("user__username", flat=True)
                .distinct()
            )
            if len(user_handles) == 1:
                user = User.objects.filter(username=user_handles[0]).first()
                if user:
                    version.author = user
        version.save()


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0051_remove_codelistversion_draft_owner"),
        ("opencodelists", "0007_auto_20210114_1139"),
    ]

    operations = [
        migrations.RunPython(
            set_author_for_under_review_versions, reverse_code=migrations.RunPython.noop
        )
    ]
