# Generated by Django 4.0.3 on 2022-04-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0052_add_author_to_under_review_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelist",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
