# Generated by Django 4.0.3 on 2022-05-04 20:01

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("codelists", "0053_codelist_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelist",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
