# Generated by Django 4.1.1 on 2022-10-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0054_codelist_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelistversion",
            name="coding_system_version_slug",
            field=models.SlugField(default="unknown", max_length=255),
            preserve_default=False,
        ),
    ]
