# Generated by Django 4.1.2 on 2022-11-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("versioning", "0003_rename_slug_codingsystemrelease_database_alias_and_more"),
        ("codelists", "0054_codelist_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelistversion",
            name="coding_system_release",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codelist_versions",
                to="versioning.codingsystemrelease",
            ),
            preserve_default=False,
        ),
    ]
