# Generated by Django 4.1.1 on 2022-10-21 07:21
from datetime import date
from django.db import migrations


def add_initial_coding_system_release(apps, schema_editor):
    CodingSystemRelease = apps.get_model("versioning", "CodingSystemRelease")
    CodelistVersion = apps.get_model("codelists", "CodelistVersion")
    initial_releases = {
        release.coding_system: release
        for release in CodingSystemRelease.objects.filter(release_name="unknown")
    }

    for coding_system in ["opcs4", "null"]:
        release, _ = CodingSystemRelease.objects.get_or_create(
            coding_system=coding_system,
            release_name="unknown",
            valid_from=date(1900, 1, 1),
            database_alias=f"{coding_system}_unknown_19000101",
        )
        initial_releases[coding_system] = release

    for clv in CodelistVersion.objects.all():
        clv.coding_system_release = initial_releases[clv.codelist.coding_system_id]
        clv.save()


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0055_codelistversion_coding_system_release"),
        ("versioning", "0003_rename_slug_codingsystemrelease_database_alias_and_more"),
    ]

    operations = [
        migrations.RunPython(
            add_initial_coding_system_release, migrations.RunPython.noop
        ),
    ]
