# Generated by Django 4.1.1 on 2022-10-21 07:21

from django.db import migrations


def add_initial_coding_system_version(apps, schema_editor):
    CodingSystemVersion = apps.get_model("versioning", "CodingSystemVersion")
    CodelistVersion = apps.get_model("codelists", "CodelistVersion")
    initial_versions = dict(
        CodingSystemVersion.objects.filter(version="unknown").values_list(
            "coding_system", "slug"
        )
    )
    initial_versions.update({"opcs4": "none", "null": "none"})

    for clv in CodelistVersion.objects.all():
        clv.coding_system_version_slug = initial_versions[clv.codelist.coding_system_id]
        clv.save()


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0055_codelistversion_coding_system_version_slug"),
        ("versioning", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            add_initial_coding_system_version, migrations.RunPython.noop
        ),
    ]
