# Generated by Django 4.1.3 on 2022-11-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versioning", "0004_codingsystemrelease_state"),
        ("codelists", "0056_data_migration_add_coding_system_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelistversion",
            name="compatible_releases",
            field=models.ManyToManyField(to="versioning.codingsystemrelease"),
        ),
    ]
