# Generated by Django 4.2.4 on 2023-11-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codelists", "0057_codelistversion_compatible_releases"),
    ]

    operations = [
        migrations.AddField(
            model_name="codelistversion",
            name="cached_csv_data",
            field=models.JSONField(default=dict),
        ),
    ]
