# Generated by Django 5.1.8 on 2025-04-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0058_codelistversion_cached_csv_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='search',
            unique_together=set(),
        ),
    ]
