# Generated by Django 5.1.7 on 2025-04-08 15:55

""" Hand-written migration to remove vestigial coding system database tables
from the core database. These were migrated out to separate versioned coding
system databases. Now we can clean up the tables from the core DB and then (in
a separate migration as it needs to be outside a transaction) VACUUM to free
some space."""

from django.db import migrations

table_names = [
    "snomedct_concept",
    "snomedct_description",
    "snomedct_relationship",
    "bnf_concept",
    "ctv3_rawterm",
    "ctv3_tppconcept",
    "ctv3_tpprelationship",
    "ctv3_rawconcepttermmapping",
    "ctv3_rawconcepthierarchy",
    "ctv3_rawconcept",
    "icd10_concept",
    "dmd_availabilityrestriction",
    "dmd_basisofname",
    "dmd_basisofstrnth",
    "dmd_colour",
    "dmd_combinationpackind",
    "dmd_combinationprodind",
    "dmd_controldrugcategory",
    "dmd_dfindicator",
    "dmd_discontinuedind",
    "dmd_dnd",
    "dmd_dtpaymentcategory",
    "dmd_flavour",
    "dmd_form",
    "dmd_ing",
    "dmd_legalcategory",
    "dmd_licensingauthority",
    "dmd_licensingauthoritychangereason",
    "dmd_namechangereason",
    "dmd_ontformroute",
    "dmd_pricebasis",
    "dmd_reimbursementstatus",
    "dmd_route",
    "dmd_speccont",
    "dmd_supplier",
    "dmd_unitofmeasure",
    "dmd_virtualproductnonavail",
    "dmd_virtualproductpresstatus",
    "dmd_vtm",
    "dmd_vpi",
    "dmd_vmpp",
    "dmd_vmp",
    "dmd_reimbinfo",
    "dmd_priceinfo",
    "dmd_prescribinfo",
    "dmd_packinfo",
    "dmd_ont",
    "dmd_licroute",
    "dmd_gtin",
    "dmd_dtinfo",
    "dmd_droute",
    "dmd_dform",
    "dmd_controlinfo",
    "dmd_aping",
    "dmd_apinfo",
    "dmd_ampp",
    "dmd_amp",
]
drop_table_statements = "\n".join([f"DROP TABLE IF EXISTS {table_name};" for table_name in table_names])

class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0058_codelistversion_cached_csv_data'),
    ]

    operations = [
        migrations.RunSQL(
            sql=drop_table_statements,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
