# Generated by Django 5.1.8 on 2025-04-10 11:16

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.utils.text import slugify


def update_search_slug(apps: Apps, schema_editor: BaseDatabaseSchemaEditor, is_new_method = True):
    search_model = apps.get_model("codelists", "Search").objects.using(schema_editor.connection.alias)

    # Get all searches
    searches = search_model.all()

    # Update each search's slug
    for search in searches:
        if search.term is not None:
            new_slug = search.term.strip().lower() if is_new_method else slugify(search.term)
        else:
            new_slug = f"code:{search.code}"

        if new_slug == search.slug:
            # They're the same so no need to update
            continue

        # There are certain situations where we can't update the slug without breaching the
        # UNIQUE constraint on the (version_id, slug) fields. See forwards_func and backwards_func for more details
        num_existing_slugs_in_this_search = search_model.filter(version_id=search.version_id,slug=new_slug).count()
        if num_existing_slugs_in_this_search:
            print(f'\nThe search with version_id={search.version_id} already has the slug "{new_slug}" in the db (term:{search.term}, code:{search.code}). Ignoring...')
            continue

        search.slug = new_slug
        search.save()


def forwards_func(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    update_search_slug(apps, schema_editor, is_new_method=True)

    # There is an obscure scenario where the new slugs fail the UNIQUE constraint
    # It occurs for someone who has searched for "Code:xxx" and "code:xxx" in the
    # same codelist. The first one is treated like a search term, and so is slugged
    # to "codexxx", while the latter is treated as a code search and slugged as
    # "code:xxx". When applying our new slug function these end up with the same
    # slug. This has only occurred once at the point this migration was first run
    # but we defend against it by just not updating the slug. There is a ticket to
    # fix the issue because "Code:xxx" should probably be case-insensitive. Also
    # changes to the search box may mean users no longer manually add the prefix.



def backwards_func(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    update_search_slug(apps, schema_editor, is_new_method=False)

    # Reversing isn't quite as straightforward. The new way allows you to have
    # two searches like "aspirin" and "aspirin*". But in the old way these would
    # have the same slug and so not be allowed. So for these we just leave the slug
    # as-is.
    # This will only happen for any searches created after the migration was first run.
    # Given the most likely time to reverse a migration will be shortly after it is applied
    # I reckon this is fine.

class Migration(migrations.Migration):
    dependencies = [
        ("codelists", "0058_codelistversion_cached_csv_data"),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
