# Generated by Django 5.1.8 on 2025-04-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0001_squashed_0059_20250423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='code',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='term',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
