# Generated by Django 5.1.7 on 2025-04-08 16:14
"""See 0059."""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0059_drop_vestigial_coding_system_tables'),
    ]

    # Disable transactions for this migration -- VACUUM cannot be run inside a
    # transaction.
    atomic = False

    operations = [
        migrations.RunSQL(
            sql="VACUUM;",
            reverse_sql=migrations.RunSQL.noop,
        ),

    ]
