# Generated by Django 5.1.9 on 2025-05-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0060_alter_search_code_alter_search_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelist',
            name='coding_system_id',
            field=models.CharField(choices=[('bnf', 'Pseudo BNF'), ('ctv3', 'CTV3 (Read V3)'), ('dmd', 'Dictionary of Medicines and Devices'), ('icd10', 'ICD-10'), ('null', 'No coding system'), ('opcs4', 'OPCS-4'), ('readv2', 'Read V2'), ('snomedct', 'SNOMED CT (UK Clinical Edition)')], max_length=32, verbose_name='Coding system'),
        ),
    ]
