# Generated by Django 5.1.9 on 2025-06-04 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0061_alter_codelist_coding_system_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="term",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
