# Generated by Django 5.1.10 on 2025-06-11 15:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0061_alter_codelist_coding_system_id'),
        ('opencodelists', '0001_squashed_0009_20250423'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='handle',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Codelist names must be non-blank, and contain only letters, numbers, underscores, or hyphens.', regex='^[\\w _-]+$')]),
        ),
        migrations.AlterField(
            model_name='handle',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handles', to='opencodelists.organisation'),
        ),
        migrations.AlterField(
            model_name='handle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handles', to=settings.AUTH_USER_MODEL),
        ),
    ]
