# Generated by Django 5.1.11 on 2025-06-20 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0062_alter_search_code_alter_search_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handle',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Codelist names must contain at least one letter or number.', regex='[a-zA-Z0-9]+')]),
        ),
    ]
