# Generated by Django 5.1.11 on 2025-07-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelists', '0063_alter_handle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the cluster', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimilaritySignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.JSONField(help_text='MinHash signature as list of integers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_signature', to='codelists.codelistversion')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarityClusterMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_to_centroid', models.FloatField(help_text='Similarity score to cluster centroid (0.0 to 1.0)')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='codelists.similaritycluster')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='codelists.codelistversion')),
            ],
            options={
                'unique_together': {('cluster', 'version')},
            },
        ),
    ]
