# Generated by Django 5.2.7 on 2025-11-28 12:01

from django.db import migrations

from codelists.coding_systems import CODING_SYSTEMS
from coding_systems.base.import_data_utils import update_codelist_version_compatibility, update_coding_system_database_connections
from coding_systems.versioning.models import CodingSystemRelease


def rebuild_compatible_releases(apps, schema_editor):
    update_coding_system_database_connections(True)
    for coding_system in CODING_SYSTEMS:
        for i, release in enumerate(
            CodingSystemRelease.objects.filter(coding_system=coding_system).order_by(
                "valid_from"
            )
        ):
            if i == 0:
                continue
            update_codelist_version_compatibility(coding_system, release.database_alias)


class Migration(migrations.Migration):
    dependencies = [
        ("codelists", "0063_alter_handle_name"),
    ]

    operations = [
        migrations.RunPython(
            rebuild_compatible_releases, reverse_code=migrations.RunPython.noop
        ),
    ]
