# Generated by Django 4.1.1 on 2022-10-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodingSystemVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coding_system", models.CharField(max_length=10)),
                ("version", models.CharField(blank=True, max_length=255, null=True)),
                ("valid_from", models.DateField()),
                ("import_timestamp", models.DateTimeField(auto_now_add=True)),
                ("import_ref", models.TextField()),
            ],
            options={
                "unique_together": {("coding_system", "valid_from")},
            },
        ),
    ]
