# Generated by Django 4.1.1 on 2022-10-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodingSystemVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coding_system", models.CharField(max_length=10)),
                ("version", models.CharField(max_length=255)),
                ("valid_from", models.DateField()),
                ("import_timestamp", models.DateTimeField(auto_now_add=True)),
                ("import_ref", models.TextField()),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "unique_together": {("coding_system", "version", "valid_from")},
            },
        ),
    ]
