# Generated by Django 5.1.8 on 2025-04-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('versioning', '0001_initial'), ('versioning', '0002_rename_codingsystemversion_codingsystemrelease'), ('versioning', '0003_rename_slug_codingsystemrelease_database_alias_and_more'), ('versioning', '0004_codingsystemrelease_state')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSystemRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding_system', models.CharField(max_length=10)),
                ('release_name', models.CharField(max_length=255)),
                ('valid_from', models.DateField()),
                ('import_timestamp', models.DateTimeField(auto_now_add=True)),
                ('import_ref', models.TextField()),
                ('database_alias', models.SlugField(max_length=255, unique=True)),
                ('state', models.CharField(choices=[('importing', 'Importing'), ('ready', 'Ready')], max_length=9)),
            ],
            options={
                'unique_together': {('coding_system', 'release_name', 'valid_from')},
            },
        ),
    ]
