# Generated by Django 4.1.2 on 2022-11-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("versioning", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CodingSystemVersion",
            new_name="CodingSystemRelease",
        ),
    ]
