# Generated by Django 4.1.3 on 2022-11-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versioning", "0003_rename_slug_codingsystemrelease_database_alias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="codingsystemrelease",
            name="state",
            field=models.CharField(
                choices=[("importing", "Importing"), ("ready", "Ready")],
                default="ready",
                max_length=9,
            ),
            preserve_default=False,
        ),
    ]
