# Generated by Django 5.2.4 on 2025-07-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0001_squashed_0004_20250425'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCDRefsetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('import_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
