# Generated by Django 5.1.12 on 2025-09-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0005_pcdrefsetversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NHSDrugRefsetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('import_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-release_date'],
                'abstract': False,
            },
        ),
    ]
