# Generated by Django 5.1.8 on 2025-04-23 13:25

import django.db.models.deletion
import django.db.models.functions.text
import opencodelists.models
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# opencodelists.migrations.0005_auto_20201112_1231


class Migration(migrations.Migration):
    replaces = [
        ("opencodelists", "0001_initial"),
        ("opencodelists", "0002_auto_20200424_1017"),
        ("opencodelists", "0003_delete_project"),
        ("opencodelists", "0004_auto_20201112_1200"),
        ("opencodelists", "0005_auto_20201112_1231"),
        ("opencodelists", "0006_remove_user_organisation"),
        ("opencodelists", "0007_auto_20210114_1139"),
        ("opencodelists", "0008_alter_user_username"),
        ("opencodelists", "0009_alter_user_options"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.SlugField(error_messages={'unique': 'A user with this username already exists.'}, primary_key=True, serialize=False, validators=[opencodelists.models.validate_username])),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email address already exists.'}, max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'ordering': (django.db.models.functions.text.Lower('username'),),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='opencodelists.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organisation')},
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='users',
            field=models.ManyToManyField(related_name='organisations', through='opencodelists.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
