# Generated by Django 3.1.3 on 2020-11-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codelists", "0014_remove_codelist_project"),
        ("opencodelists", "0002_auto_20200424_1017"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
