# Generated by Django 3.1.3 on 2020-11-12 12:31

from django.db import migrations

from ..actions import add_user_to_organisation


def add_opensafely_users_to_organisation(apps, schema_editor):
    Organisation = apps.get_model("opencodelists", "Organisation")
    User = apps.get_model("opencodelists", "User")

    opensafely = Organisation.objects.get(slug="opensafely")

    for user in User.objects.filter(organisation_id__in=["ebm-datalab", "lshtm"]):
        membership = add_user_to_organisation(
            user=user,
            organisation=opensafely,
            date_joined="2020-11-12",
        )
        membership.is_admin = user.is_admin
        membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ("opencodelists", "0004_auto_20201112_1200"),
    ]

    operations = [migrations.RunPython(add_opensafely_users_to_organisation)]
