# Generated by Django 3.1.3 on 2020-11-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opencodelists", "0005_auto_20201112_1231"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="organisation",
        ),
    ]
