# Generated by Django 3.1.5 on 2021-01-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencodelists", "0006_remove_user_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "A user with this email address already exists."
                },
                max_length=255,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.SlugField(
                error_messages={"unique": "A user with this username already exists."},
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
