# Generated by Django 4.1.3 on 2023-02-17 13:55

from django.db import migrations, models
import opencodelists.models


class Migration(migrations.Migration):

    dependencies = [
        ("opencodelists", "0007_auto_20210114_1139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.SlugField(
                error_messages={"unique": "A user with this username already exists."},
                primary_key=True,
                serialize=False,
                validators=[opencodelists.models.validate_username],
            ),
        ),
    ]
