# Generated by Django 4.2.17 on 2024-12-20 15:51
import csv
import os
from datetime import datetime
from pathlib import Path

from django.db import migrations
from django.db.models import F


def remove_spam_users(apps, schema_editor):
    User = apps.get_model("opencodelists", "User")

    # make lists of users we definitely don't want to remove
    Handle = apps.get_model("codelists", "Handle")
    users_with_codelists = {h.user for h in Handle.objects.all()}
    uk_users = User.objects.filter(email__endswith="uk")
    edu_users = User.objects.filter(email__regex=r"[^@]+@.*(:?\.edu)(:?\.[^\.]+)?")
    ac_users = User.objects.filter(email__regex=r"[^@]+@.*(:?\.ac)(:?\.[^\.]+)+")
    admins = User.objects.filter(is_admin=True)
    removal_candidates = (
        User.objects.exclude(users_with_codelists)
        .exclude(uk_users)
        .exclude(edu_users)
        .exclude(ac_users)
        .exclude(admins)
    )
    print(f"Users eligibile for removal {len(removal_candidates)}")

    users_to_remove = set()

    # heuristics for spammy users
    # too many dots
    three_dots_before_at = r"(?:[^\.]+\.){3,}[^\@]*\@.*"
    dotty = removal_candidates.filter(email__regex=three_dots_before_at)
    print(f"Three-or-more dots before @ users {len(dotty)}")
    users_to_remove |= {dotty}

    # bad TLDs
    for bad_tld in [
        ".dynainbox.com",
        ".fun",
        ".mo",
        ".online",
        ".pl",
        ".ru",
        ".shop",
        ".site",
        ".space",
        ".store",
        ".ua",
        "hotmails.com",
    ]:
        badtldusers = removal_candidates.filter(email__endswith=bad_tld)
        print(f"{bad_tld} email domain users {len(badtldusers)}")
        users_to_remove |= {bad_tld}

    # username equals name and no space in either
    badnames = removal_candidates.objects.filter(username=F("name")).exclude(
        name__contains=" "
    )
    print(f"username equals name and no space in either {len(badnames)}")
    users_to_remove |= badnames

    print(f"Combined users to be removed {len(users_to_remove)}")
    userfields = [f.name for f in User._meta.fields]

    # dump them to csv just in case
    dump_path = Path(os.environ["DATABASE_DIR"]) / "deleted-user-dumps"
    dump_path.mkdir(parents=False, exist_ok=True)
    with (dump_path / f"deletedusers_{datetime.now().isoformat()}.csv").open("w") as f:
        writer = csv.DictWriter(f, fieldnames=userfields)
        writer.writeheader()
        writer.writerows(
            [{f: getattr(u, f) for f in userfields} for u in users_to_remove]
        )

    for u in users_to_remove:
        u.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("opencodelists", "0009_alter_user_options"),
    ]

    operations = [migrations.RunPython(remove_spam_users, migrations.RunPython.noop)]
