# Generated by Django 5.1.8 on 2025-04-25 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('bnf', '0001_initial'), ('bnf', '0002_auto_20200930_0928')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bnf.concept')),
            ],
        ),
    ]
