# Generated by Django 3.0.7 on 2020-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='code',
            field=models.TextField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chemicalsubstance',
            name='code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chemicalsubstance',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.TextField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subparagraph',
            name='code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subparagraph',
            name='name',
            field=models.TextField(),
        ),
    ]
