# Generated by Django 3.1.1 on 2020-09-30 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bnf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "code",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=18)),
                ("name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="bnf.concept",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Chapter",
        ),
        migrations.DeleteModel(
            name="ChemicalSubstance",
        ),
        migrations.DeleteModel(
            name="Paragraph",
        ),
        migrations.DeleteModel(
            name="Presentation",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
        migrations.DeleteModel(
            name="Subparagraph",
        ),
    ]
