# Generated by Django 5.2.17 on 2026-09-07 15:08

from django.db import migrations
from datetime import date

def delete_bnf_coding_system_release(apps, schema_editor):
    """Delete BNF CodingSystemRelease with name `dafadfads` and associated CodelistVersions."""

    CodingSystemRelease = apps.get_model("versioning", "CodingSystemRelease")
    CodelistVersion = apps.get_model("codelists", "CodelistVersion")

    try:
        bnf_coding_system_release = CodingSystemRelease.objects.get(
        coding_system="bnf",
        release_name="90 (2026-09-01)",
        valid_from=date(2026, 9, 1)
        )
    except CodingSystemRelease.DoesNotExist:
        print("0002: No BNF CodingSystemRelease '90 (2026-09-01)', nothing to do")
        return

    # Deleting a CodingSystemRelease deletes any CodelistVersions created with this release via CASCADE.
    codelist_versions = CodelistVersion.objects.filter(
    coding_system_release=bnf_coding_system_release
    )

    print("CodelistVersions to be deleted:")
    for version in codelist_versions:
        print(version.pk)

    deleted_count, deleted_objects = bnf_coding_system_release.delete()

    # Provide some feedback.
    print(f"Deleted {deleted_count} objects:")
    print(deleted_objects)



class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_delete_codelists_without_handles'),
    ]

    operations = [
        migrations.RunPython(delete_bnf_coding_system_release, migrations.RunPython.noop)
    ]
