# Generated by Django 3.0.7 on 2020-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rctctv3map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='ctv3_concept_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='ctv3_term_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='ctv3_termtyp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='map_typ',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='stat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='use_ctv3_term_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='v2_concept_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapping',
            name='v2_term_id',
            field=models.TextField(db_index=True),
        ),
    ]
