# Generated by Django 3.1.1 on 2020-09-28 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("snomedct", "0003_auto_20200806_1428"),
        ("ctv3", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mapping",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("ctv3_term_type", models.CharField(max_length=1)),
                ("map_status", models.BooleanField()),
                ("effective_date", models.DateField()),
                ("is_assured", models.BooleanField()),
                (
                    "ctv3_concept",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snomedct_mappings",
                        to="ctv3.rawconcept",
                    ),
                ),
                (
                    "ctv3_term",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snomedct_mappings",
                        to="ctv3.rawterm",
                    ),
                ),
                (
                    "sct_concept",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ctv3_mappings",
                        to="snomedct.concept",
                    ),
                ),
                (
                    "sct_description",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ctv3_mappings",
                        to="snomedct.description",
                    ),
                ),
            ],
        ),
    ]
