# Generated by Django 3.0.7 on 2020-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctv3sctmap2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='ctv3_term_type',
            field=models.TextField(),
        ),
    ]
