# Generated by Django 3.1.2 on 2020-11-06 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bnf", "0002_auto_20200930_0928"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mapping",
            fields=[
                (
                    "dmd_code",
                    models.CharField(max_length=18, primary_key=True, serialize=False),
                ),
                ("dmd_type", models.CharField(max_length=4)),
                (
                    "bnf_concept",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bnf_mappings",
                        to="bnf.concept",
                    ),
                ),
            ],
        ),
    ]
