from glob import glob

from django.db import transaction
from django.db.models import Q

from codelists.actions import create_old_style_version
from codelists.models import Handle


@transaction.atomic
def run(owner_path):
    """Create a new version for each codelist with a CSV in `owner_path`.

    New versions are under review.

    CSVs were generated by normalise_codelists.py in
    https://github.com/opensafely/dmd-codelist-report.
    """

    for path in glob(f"{owner_path}/*.csv"):
        with open(path) as f:
            csv_data = f.read()
        owner_id = path.split("/")[-2]
        slug = path.split("/")[-1].split(".")[0]
        handle = Handle.objects.filter(
            Q(user_id=owner_id) | Q(organisation_id=owner_id)
        ).get(slug=slug)
        codelist = handle.codelist
        prev_clv = codelist.versions.order_by("-id")[0]
        new_clv = create_old_style_version(codelist=codelist, csv_data=csv_data)
        print(f"{owner_id},{slug},{prev_clv.hash},{new_clv.hash}")
