# Generated by Django 5.1.8 on 2025-04-25 13:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('builder', '0001_initial'), ('builder', '0002_auto_20200929_1649'), ('builder', '0003_auto_20210506_1345')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    ]
