# Generated by Django 3.1.1 on 2020-09-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftcodelist",
            name="coding_system_id",
            field=models.CharField(
                choices=[
                    ("snomedct", "SNOMED CT"),
                    ("ctv3", "CTV3 (Read V3)"),
                    ("bnf", "Pseudo BNF"),
                ],
                max_length=32,
                verbose_name="Coding system",
            ),
        ),
    ]
