# Generated by Django 3.0.7 on 2020-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftcodelist',
            name='coding_system_id',
            field=models.TextField(choices=[('snomedct', 'SNOMED CT')], verbose_name='Coding system'),
        ),
        migrations.AlterField(
            model_name='draftcodelist',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='term',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='status',
            field=models.TextField(choices=[('?', 'Undecided'), ('!', 'In conflict'), ('+<', 'Included with descendants'), ('(+)', 'Included by ancestor'), ('-<', 'Excluded with descendants'), ('(-)', 'Excluded by ancestor')], default='?'),
        ),
    ]
