# Generated by Django 3.1.8 on 2021-05-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0002_auto_20200929_1649"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="draftcodelist",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="draftcodelist",
            name="owner",
        ),
        migrations.AlterUniqueTogether(
            name="search",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="search",
            name="codelist",
        ),
        migrations.AlterUniqueTogether(
            name="searchresult",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="searchresult",
            name="code",
        ),
        migrations.RemoveField(
            model_name="searchresult",
            name="search",
        ),
        migrations.DeleteModel(
            name="Code",
        ),
        migrations.DeleteModel(
            name="DraftCodelist",
        ),
        migrations.DeleteModel(
            name="Search",
        ),
        migrations.DeleteModel(
            name="SearchResult",
        ),
    ]
