# Generated by Django 2.2.11 on 2020-03-31 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "read_code",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "term_id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("name_1", models.CharField(max_length=30)),
                ("name_2", models.CharField(max_length=60, null=True)),
                ("name_3", models.CharField(max_length=198, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConceptTermMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="readv2.Concept"
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="readv2.Term"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConceptHierarchy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_links",
                        to="readv2.Concept",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_links",
                        to="readv2.Concept",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="concept",
            name="children",
            field=models.ManyToManyField(
                related_name="parents",
                through="readv2.ConceptHierarchy",
                to="readv2.Concept",
            ),
        ),
        migrations.AddField(
            model_name="concept",
            name="terms",
            field=models.ManyToManyField(
                related_name="concepts",
                through="readv2.ConceptTermMapping",
                to="readv2.Term",
            ),
        ),
    ]
