# Generated by Django 5.1.8 on 2025-04-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    # replaces = [('readv2', '0001_initial'), ('readv2', '0002_auto_20200429_1216'), ('readv2', '0003_concept'), ('readv2', '0004_delete_concept')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
