# Generated by Django 2.2.11 on 2020-04-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readv2', '0002_auto_20200429_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('read_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name_1', models.CharField(max_length=30)),
                ('name_2', models.CharField(max_length=60)),
                ('name_3', models.CharField(max_length=198)),
                ('unknown_field_4', models.CharField(max_length=15)),
                ('unknown_field_5', models.CharField(max_length=2)),
                ('unknown_field_6', models.CharField(max_length=13)),
                ('unknown_field_7', models.CharField(max_length=2)),
                ('unknown_field_8', models.CharField(max_length=19)),
                ('unknown_field_9', models.CharField(max_length=2)),
                ('speciality_flags', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=1)),
                ('language', models.CharField(max_length=2)),
            ],
        ),
    ]
