# Generated by Django 3.0.7 on 2020-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readv2', '0003_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='language',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concept',
            name='read_code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='concept',
            name='speciality_flags',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concept',
            name='status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concept',
            name='unknown_field_4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concept',
            name='unknown_field_5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concept',
            name='unknown_field_6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concept',
            name='unknown_field_7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concept',
            name='unknown_field_8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concept',
            name='unknown_field_9',
            field=models.TextField(),
        ),
    ]
