# Generated by Django 4.1.3 on 2022-11-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("readv2", "0003_concept"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Concept",
        ),
    ]
