# Generated by Django 5.1.8 on 2025-04-25 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('snomedct', '0001_initial'), ('snomedct', '0002_historysubstitution_querytablerecord'), ('snomedct', '0003_auto_20200806_1428'), ('snomedct', '0004_remove_querytablerecord_and_historysubstitution')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField()),
                ('definition_status', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.concept')),
                ('module', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.concept')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField()),
                ('relationship_group', models.CharField(max_length=3)),
                ('characteristic_type', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.concept')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='snomedct.concept')),
                ('modifier', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.concept')),
                ('module', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.concept')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_relationships', to='snomedct.concept')),
                ('type', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.concept')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='sources',
            field=models.ManyToManyField(related_name='destinations', through='snomedct.Relationship', to='snomedct.concept'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField()),
                ('language_code', models.CharField(max_length=3)),
                ('term', models.CharField(max_length=255)),
                ('case_significance', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.concept')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='snomedct.concept')),
                ('module', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.concept')),
                ('type', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.concept')),
            ],
        ),
    ]
