# Generated by Django 2.2.11 on 2020-04-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField()),
                ('definition_status', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.Concept')),
                ('module', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.Concept')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('effective_time', models.CharField(max_length=8)),
                ('active', models.BooleanField()),
                ('relationship_group', models.CharField(max_length=3)),
                ('characteristic_type', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.Concept')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='snomedct.Concept')),
                ('modifier', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.Concept')),
                ('module', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.Concept')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_relationships', to='snomedct.Concept')),
                ('type', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.Concept')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('effective_time', models.CharField(max_length=8)),
                ('active', models.BooleanField()),
                ('language_code', models.CharField(max_length=3)),
                ('term', models.CharField(max_length=255)),
                ('case_significance', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.Concept')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='snomedct.Concept')),
                ('module', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.Concept')),
                ('type', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snomedct.Concept')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='sources',
            field=models.ManyToManyField(related_name='destinations', through='snomedct.Relationship', to='snomedct.Concept'),
        ),
    ]
