# Generated by Django 3.0.7 on 2020-08-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0002_historysubstitution_querytablerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='effective_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='effective_time',
            field=models.DateField(),
        ),
    ]
