# Generated by Django 3.0.7 on 2020-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0002_historysubstitution_querytablerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='description',
            name='effective_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='description',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='description',
            name='language_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='description',
            name='term',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historysubstitution',
            name='new_concept_fsn',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historysubstitution',
            name='new_concept_status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historysubstitution',
            name='old_concept_fsn',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historysubstitution',
            name='old_concept_status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historysubstitution',
            name='path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='effective_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_group',
            field=models.TextField(),
        ),
    ]
