# Generated by Django 4.1.2 on 2022-11-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snomedct", "0003_auto_20200806_1428"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="querytablerecord",
            name="subtype",
        ),
        migrations.RemoveField(
            model_name="querytablerecord",
            name="supertype",
        ),
        migrations.DeleteModel(
            name="HistorySubstitution",
        ),
        migrations.DeleteModel(
            name="QueryTableRecord",
        ),
    ]
