# Generated by Django 5.2.4 on 2025-07-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0001_squashed_0004_20250425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='sources',
            field=models.ManyToManyField(related_name='destinations', through='snomedct.Relationship', through_fields=('destination', 'source'), to='snomedct.concept'),
        ),
    ]
