# Generated by Django 5.2.9 on 2025-12-31 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('year', models.IntegerField()),
                ('source_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='modifier_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='modifier_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='kind',
            field=models.CharField(choices=[('chapter', 'Chapter'), ('block', 'Block'), ('category', 'Category')], max_length=8),
        ),
        migrations.AddField(
            model_name='concept',
            name='editions',
            field=models.ManyToManyField(to='icd10.edition'),
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('inclusion', 'Inclusion'), ('exclusion', 'Exclusion'), ('note', 'Note'), ('text', 'Text')], max_length=9)),
                ('text', models.TextField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='icd10.concept')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=200)),
                ('modifier_4', models.CharField(blank=True, max_length=200, null=True)),
                ('modifier_5', models.CharField(blank=True, max_length=200, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='icd10.concept')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='icd10.edition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('concept', 'edition'), name='concept_edition_uq_together')],
            },
        ),
    ]
