# Generated by Django 5.2.14 on 2026-06-01 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('year', models.IntegerField()),
                ('source_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('chapter', 'Chapter'), ('block', 'Block'), ('category', 'Category')], max_length=8)),
                ('usage', models.CharField(choices=[('dagger', 'Dagger'), ('asterisk', 'Asterisk'), ('normal', 'Normal')], max_length=8)),
                ('term', models.CharField(blank=True, max_length=255)),
                ('term_modifier', models.CharField(blank=True, max_length=255, null=True)),
                ('modifier_position', models.IntegerField(blank=True, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_editions', to='icd10.concept')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_editions', to='icd10.edition')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('inclusion', 'Inclusion'), ('exclusion', 'Exclusion'), ('note', 'Note'), ('text', 'Text')], max_length=9)),
                ('text', models.TextField()),
                ('concept_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='icd10.conceptedition')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='editions',
            field=models.ManyToManyField(through='icd10.ConceptEdition', to='icd10.edition'),
        ),
        migrations.CreateModel(
            name='ModifierRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('inclusion', 'Inclusion'), ('exclusion', 'Exclusion'), ('note', 'Note'), ('text', 'Text')], max_length=9)),
                ('text', models.TextField()),
                ('concept_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_rubrics', to='icd10.conceptedition')),
            ],
        ),
        migrations.CreateModel(
            name='DaggerAsteriskRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asterisk_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dagger_relations', to='icd10.conceptedition')),
                ('dagger_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asterisk_relations', to='icd10.conceptedition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dagger_concept', 'asterisk_concept'), name='dagger_asterisk_uq_together')],
            },
        ),
        migrations.AddConstraint(
            model_name='conceptedition',
            constraint=models.UniqueConstraint(fields=('concept', 'edition'), name='concept_edition_uq_together'),
        ),
        migrations.AddConstraint(
            model_name='conceptedition',
            constraint=models.CheckConstraint(condition=models.Q(('modifier_position__in', [4, 5])), name='modifier_position_4_or_5'),
        ),
    ]
