# Generated by Django 5.2.14 on 2026-05-20 15:51

from django.db import migrations
from coding_systems.icd10.models import Concept, ConceptEdition, ConceptKind, ConceptUsage, Edition
from coding_systems.versioning.models import CodingSystemRelease


def move_concept_fields_to_conceptedition(apps, schema_editor):
    for csr in CodingSystemRelease.objects.filter(coding_system="icd10"):
        previous_2019_edition, created = Edition.objects.using(csr.database_alias).get_or_create(
            id="2019-covid-no-mods",
            version="20190101",
            year="2019",
            source_description=""",
        Loaded in ClaML format from icd website.
        No modifiers, rubrics, or dagger/asterisk pairs.""",
        )
        if not created:
            continue
        ConceptEdition.objects.using(csr.database_alias).bulk_create(
            [
                ConceptEdition(
                    concept=c,
                    edition=previous_2019_edition,
                    kind=ConceptKind(c.kind),
                    term=c.term,
                    usage=ConceptUsage.NORMAL,
                )
                for c in Concept.objects.using(csr.database_alias).all()
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("icd10", "0002_edition_conceptedition_concept_editions_rubric_and_more"),
    ]

    operations = [
        migrations.RunPython(
            move_concept_fields_to_conceptedition,
            reverse_code=migrations.RunPython.noop,
        )
    ]
