# Generated by Django 5.2.14 on 2026-05-20 15:51

from django.db import migrations, utils
from coding_systems.icd10.models import Concept, ConceptUsage, Edition
from coding_systems.versioning.models import CodingSystemRelease


def move_concept_fields_to_conceptedition(apps, schema_editor):
    try:
        schema_editor.execute("SELECT kind FROM icd10_concept LIMIT 1;")
    except utils.OperationalError:
        # If the query fails, it means the "kind" column doesn't exist
        # which means that the later migration to remove this column
        # has already been applied, so we can skip this migration.
        return

    database_alias = schema_editor.connection.alias

    if not Concept.objects.using(database_alias).exists():
        # If no concepts this must be a new release, so we don't need to create
        # an edition for the previous release, or migrate the concepts.
        return

    version = database_alias.split("_")[-1]
    edition, created = Edition.objects.using(database_alias).get_or_create(
        id=database_alias,
        version=version,
        year=version[:4],
        source_description=f"Edition for previous release {database_alias}"
    )

    if not created:
        # If the edition already exists, it means this migration has already been applied
        # to this database, so we can skip it.
        return

    schema_editor.execute("""
        INSERT INTO icd10_conceptedition (concept_id, edition_id, kind, term, usage)
        SELECT code, %s, kind, term, %s
        FROM icd10_concept;
    """, [edition.id, ConceptUsage.NORMAL])


class Migration(migrations.Migration):
    dependencies = [
        ("icd10", "0002_edition_conceptedition_concept_editions_rubric_and_more"),
    ]

    operations = [
        migrations.RunPython(
            move_concept_fields_to_conceptedition,
            reverse_code=migrations.RunPython.noop,
        )
    ]
