# Generated by Django 5.2.14 on 2026-05-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icd10', '0003_migrate_existing_data_to_transitional_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='term',
        ),
    ]
