name: Update Python dependencies

on:
  workflow_dispatch:
  schedule:
    - cron:  "12 6 * * 1"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update-dependencies:
    name: Update Python dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - uses: opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17 # v1.7.0
      with:
        install-just: true
        install-uv: true

    - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: generate-token
      with:
        app-id: 1031449  # opensafely-core Create PR app
        private-key: ${{ secrets.CREATE_PR_APP_PRIVATE_KEY }}
        permission-contents: write
        permission-pull-requests: write

    - uses: bennettoxford/update-dependencies-action@b77a22bcfe1d06020d908e64c9828fe944da3a5e # v1
      with:
        token: ${{ steps.generate-token.outputs.token }}
